// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbntiwffhfpqreidnhav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibnRpd2ZmaGZwcXJlaWRuaGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MTIxODQsImV4cCI6MjA3NTA4ODE4NH0.zZF4jqf019ClHrp3k5IfVpTnMn8i5iooDc8jWeVZCig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});